Explicitly ignore F_COUL14 in do_iparam
F_COUL14 is described in src/gromacs/topology/idef.h
and therefore appears as a constant in settings.py.
Yet, it does not appear in src/gromacs/fileio/tpxio.cpp.
Here we ignore it explicitly

If we do not explicitly ignore F_COUL14, then we get

    Traceback (most recent call last):

      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/test_atomselections.py", line 352, in setUp

        self.universe = MDAnalysis.Universe(TPR,XTC)

      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/core/AtomGroup.py", line 3783, in __init__

        self._topology = p.parse()

      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/topology/TPRParser.py", line 167, in parse

        tpr_top = U.do_mtop(data, V, self._u)

      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/topology/tpr/utils.py", line 153, in do_mtop

        do_ffparams(data, fver)  # params

      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/topology/tpr/utils.py", line 243, in do_ffparams

        iparams = do_iparams(data, functype, fver)

      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/topology/tpr/utils.py", line 478, in do_iparams

        raise NotImplementedError("unknown functype: {0}".format(i))

    NotImplementedError: unknown functype: 34